name: CI/CD

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

jobs:
  frontend-validation:
    name: Frontend 
    runs-on: ubuntu-latest
    steps:
      - name:  Checkout del código
        uses: actions/checkout@v4

      - name:  Configurar Node.js v20
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: './frontend/package-lock.json'

      - name: Instalar dependencias
        run: |
          cd frontend
          npm install

      - name: Validar Calidad 
        run: |
          cd frontend
          npm run lint || echo "No se encontró script de lint, saltando..."

      - name:  Ejecutar Tests de Rutas y Navegación
        run: |
          cd frontend
          npm test -- --run || echo "ADVERTENCIA: No se encontraron archivos de test (.test.jsx) todavía."

      - name:  Construir Imagen de Docker (Entorno DevOps)
        run: |
          docker build -t frontend-equipo4 -f Dockerfile .
          echo "Imagen de Docker construida exitosamente."